---
language: node_js
node_js:
  - "8"

sudo: false

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

install:
  - (cd $DIR; yarn)

script:
  - (cd $DIR; yarn test)

env:
  - JOBS=2 DIR=frontend
  - JOBS=2 DIR=backend
