version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./tools/docker/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    links:
      - backend
      - frontend
    ports:
      - "8080:80"

  backend:
    image: node:8
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - ./tools/docker/rt4/var/rt4:/var/rt4/rt4
    links:
      - redis
      - postgres
      - ldap
      # - redmine
      # - rt
      - vault
      - timedbackend
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
    ports:
      - "3000:3000"
    command: yarn watch

  frontend:
    image: node:8
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/tmp
      - /usr/src/app/dist
    ports:
      - "7020:7020"
    command: yarn start-proxy

  redis:
    image: redis
    ports:
      - "6379:6379"

  ldap:
    image: osixia/openldap
    ports:
      - "4389:389"
    volumes:
      - ./tools/docker/ldap/ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    environment:
      - LDAP_ORGANISATION=adsy
      - LDAP_DOMAIN=adsy-ext.becs.adfinis-sygroup.ch
      - LDAP_ADMIN_PASSWORD=123qwe
      - LDAP_OPENLDAP_UID=1000
      - LDAP_OPENLDAP_GID=1000
      - LDAP_TLS=false
      - LDAP_BASE_DN=dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
    command: ["--copy-service", "--loglevel", "debug"]

  ldapadmin:
    image: osixia/phpldapadmin
    volumes:
        - ./tools/docker/ldapadmin/config.php:/container/service/phpldapadmin/assets/config/config.php
    ports:
      - "6443:80"
    environment:
      #- PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
    command: ['--copy-service']

  postgres:
    image: postgres
    volumes:
      - ./tools/docker/postgres/setup/:/docker-entrypoint-initdb.d/
      - ./tools/docker/postgres/timed-test-data.sql:/tmp/timed-test-data.sql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=customercenter
    ports:
      - "5432:5432"

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin

  # User older version because the newer version does not work
  vault:
    image: vault:0.9.0
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"

  timedbackend:
    image: adfinissygroup/timed-backend
    ports:
      - '8000:80'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=psql://test:test@postgres:5432/timed
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_USER=test
      - DJANGO_DATABASE_PASSWORD=test
      - ENV=docker
      - STATIC_ROOT=/var/www/static

  gitlab:
      image: 'gitlab/gitlab-ce:latest'
      logging:
        driver: "none"
      ports:
        - '5080:80'
        - '5443:443'
        - '5022:22'

  gitlab-runner:
      image: 'gitlab/gitlab-runner:latest'
      depends_on:
        - gitlab
